impl of setup command fairly complete now

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,7 +2,7 @@
 
 function usage {
   cat <<EOF
-setup 1: sets up a new Heroku app instance linked to a branch
+setup 1: sets up a new Heroku app for branch
 
 Usage: hk setup [-b branch] [app name]
 
@@ -56,15 +56,25 @@ GITHUB_REPO=$(git config --get remote.origin.url | \
 TAR_URL=$(curl -s -u "$TOKEN:x-oauth-basic" -w "%{redirect_url}" \
           https://api.github.com/repos/$GITHUB_REPO/tarball/$BRANCH)
 
+echo "Setting up new Heroku app for branch $BRANCH in $GITHUB_REPO"
+echo -n "Starting setup..."
 START_SETUP=$(echo "{\"source_blob\": { \"url\": \"$TAR_URL\" }}" | hk api post /app-setups)
 
 SETUP_ID=$(echo $START_SETUP | jq -r .id)
 
 HAIKU_NAME=$(echo $START_SETUP | jq -r .app.name)
 
-echo "Haiku app name: $HAIKU_NAME"
-echo "Setup id: $SETUP_ID"
-echo -n "Setting up"
+if [ -z "$SETUP_ID" ]; then
+  echo " failed"
+  echo "JSON response:"
+  echo $START_SETUP
+  exit 1
+fi
+
+echo " done"
+
+echo "  (haiku app = $HAIKU_NAME, setup id = $SETUP_ID)"
+echo -n "Deploying and running scripts"
 
 while true; do 
   echo -n '.'
@@ -74,7 +84,9 @@ while true; do
   if [ "$STATUS" != "pending" ]; then
     if [ "$STATUS" == "succeeded" ]; then
       echo " done"
-      echo $SETUP_RESULT
+      echo "Post deploy script output:"
+      echo $SETUP_RESULT | jq -r .postdeploy.output
+
       break
     else
       echo " failed"
@@ -84,6 +96,16 @@ while true; do
   fi
 done
 
+# heroku rename
+function hmv {
+    new_name=$(echo "{\"name\": \"$2\"}" | hk api patch /apps/$1 | jq -r .name)
+    if [ "$2" == "$new_name" ]; then
+      echo "Renamed app to $new_name"
+    else
+      echo "App rename of $new_name failed"
+    fi
+}
+
 if [ -z "$HEROKUAPP" ]; then
   if [ "$BRANCH" == "master" ]; then
     # can't rename, so haiku name is the name
@@ -91,12 +113,11 @@ if [ -z "$HEROKUAPP" ]; then
   else
     # set name to <master app name>-<branch name> 
     HEROKUAPP="$(git config --get branch.master.heroku)-$BRANCH"
-    hk rename $HEROKUAPP -a $HAIKU_NAME
-    echo "Renamed app to $HEROKUAPP"
+    echo "Renaming from $HAIKU_NAME to $HEROKUAPP..."
+    hmv $HAIKU_NAME $HEROKUAPP
   fi
 else
-  hk rename $HEROKUAPP -a $HAIKU_NAME
-  echo "Renamed app to $HEROKUAPP"
+  hmv $HAIKU_NAME $HEROKUAPP
 fi
 
 git config branch.$BRANCH.heroku $HEROKUAPP
